name: Build and Deploy PHP

env:
  PHP_VERSION: "8.4"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer

      - name: Check if composer.json exists
        id: check_composer
        uses: andstor/file-existence-action@v3
        with:
          files: composer.json

      - name: Get Composer Cache Directory
        id: composer-cache
        if: steps.check_composer.outputs.files_exists == 'true'
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Set up dependency caching
        uses: actions/cache@v4
        if: steps.check_composer.outputs.files_exists == 'true'
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Run composer install if composer.json exists
        if: steps.check_composer.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress --no-suggest

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .
